### ISSUE TITLE
modestga: cannot start a new process

### ISSUE THREAD

**Issue by krzysztofarendt** [sdu-cfei/modest-py#65]
Happens when running `test_estimation_basic_parallel()` on Windows 10 with FMPy.

```
ERROR: test_estimation_basic_parallel (modestpy.test.test_estimation.TestEstimation)
Will use default methods ('MODESTGA', 'PS')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\modest-py\modestpy\test\test_estimation.py", line 86, in test_estimation_basic_parallel
    estimates = session.estimate()
  File "d:\code\modest-py\modestpy\estimation.py", line 299, in estimate
    m_estimates = m_inst.estimate()
  File "d:\code\modest-py\modestpy\estim\ga_parallel\ga_parallel.py", line 309, in estimate
    out = minimize(
  File "D:\code\modest-py\venv\lib\site-packages\modestga\ga.py", line 166, in minimize
    p.start()
  File "c:\users\krzys\appdata\local\programs\python\python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\krzys\appdata\local\programs\python\python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\krzys\appdata\local\programs\python\python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "c:\users\krzys\appdata\local\programs\python\python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\krzys\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "c:\users\krzys\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by krzysztofarendt** [comment]
Solved: https://github.com/sdu-cfei/modest-py/commit/4e001c42f63125a318feb0db6a27d7a82439008c
